export const EXPENSE_CATEGORIES = [
  'Food & Dining',
  'Transportation',
  'Shopping',
  'Entertainment',
  'Health & Medical',
  'Utilities',
  'Education',
  'Housing',
  'Travel',
  'Personal Care',
  'Insurance',
  'Investments',
  'EMI / Loan',
  'Groceries',
  'Other',
];

export const INCOME_CATEGORIES = [
  'Salary',
  'Freelance',
  'Business',
  'Investment Returns',
  'Rental Income',
  'Dividends',
  'Bonus',
  'Gift',
  'Other',
];

export const CATEGORY_COLORS = {
  'Food & Dining': '#f97316',
  'Transportation': '#3b82f6',
  'Shopping': '#ec4899',
  'Entertainment': '#8b5cf6',
  'Health & Medical': '#ef4444',
  'Utilities': '#6366f1',
  'Education': '#0ea5e9',
  'Housing': '#14b8a6',
  'Travel': '#f59e0b',
  'Personal Care': '#d946ef',
  'Insurance': '#64748b',
  'Investments': '#22c55e',
  'EMI / Loan': '#dc2626',
  'Groceries': '#84cc16',
  'Salary': '#10b981',
  'Freelance': '#06b6d4',
  'Business': '#8b5cf6',
  'Other': '#94a3b8',
};
